before_script:
  - apt-get update -qq && apt-get install -y -qq libcolpack-dev boost-dev

stages:
 - build

build_job:
 stage: build
 script:
    - autoreconf -fi
    - ./configure  
    - make
    - make test
